# Generated by Django 5.2.1 on 2026-01-08 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.AlterField(
            model_name='post',
            name='promotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='department',
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.department'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
